"""expand schema for csv import - 7 new tables

Revision ID: 71373059747c
Revises: b6b8d0f99604
Create Date: 2026-05-05 23:50:42.072381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71373059747c'
down_revision: Union[str, Sequence[str], None] = 'b6b8d0f99604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=50), nullable=False),
    sa.Column('first_seen_at', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_external_customer_id'), 'customers', ['external_customer_id'], unique=True)
    op.create_table('ga4_item_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interaction_date', sa.Date(), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_category', sa.String(length=100), nullable=True),
    sa.Column('item_brand', sa.String(length=100), nullable=True),
    sa.Column('item_variant', sa.String(length=100), nullable=True),
    sa.Column('item_list_name', sa.String(length=255), nullable=True),
    sa.Column('item_list_id', sa.String(length=100), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('add_to_cart_count', sa.Integer(), nullable=False),
    sa.Column('remove_from_cart_count', sa.Integer(), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('purchase_quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('checkout_count', sa.Integer(), nullable=False),
    sa.Column('refund_count', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('campaign', sa.String(length=255), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ga4_item_interactions_interaction_date'), 'ga4_item_interactions', ['interaction_date'], unique=False)
    op.create_index(op.f('ix_ga4_item_interactions_item_id'), 'ga4_item_interactions', ['item_id'], unique=False)
    op.create_table('ga4_traffic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('traffic_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('medium', sa.String(length=100), nullable=False),
    sa.Column('campaign', sa.String(length=255), nullable=True),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('session_duration', sa.BigInteger(), nullable=True),
    sa.Column('bounce_rate', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pageviews', sa.BigInteger(), nullable=False),
    sa.Column('events', sa.BigInteger(), nullable=False),
    sa.Column('event_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('conversion_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ga4_traffic_traffic_date'), 'ga4_traffic', ['traffic_date'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('size_range', sa.String(length=50), nullable=True),
    sa.Column('product_created_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_ad_breakdowns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('breakdown_date', sa.Date(), nullable=False),
    sa.Column('breakdown_type', sa.String(length=50), nullable=False),
    sa.Column('breakdown_value', sa.String(length=255), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('conversion_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_per_conversion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actions_count', sa.Integer(), nullable=False),
    sa.Column('action_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_ad_breakdowns_breakdown_date'), 'meta_ad_breakdowns', ['breakdown_date'], unique=False)
    op.add_column('ad_metrics_daily', sa.Column('reach', sa.BigInteger(), nullable=True))
    op.add_column('ad_metrics_daily', sa.Column('frequency', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('ad_metrics_daily', sa.Column('ctr', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('ad_metrics_daily', sa.Column('cpc', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ad_metrics_daily', sa.Column('cpm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ad_metrics_daily', sa.Column('actions_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ad_metrics_daily', sa.Column('segment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ad_metrics_daily', sa.Column('external_campaign_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_ad_metrics_daily_external_campaign_id'), 'ad_metrics_daily', ['external_campaign_id'], unique=False)
    op.add_column('campaigns', sa.Column('objective', sa.String(length=100), nullable=True))
    op.add_column('campaigns', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('campaigns', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('campaigns', sa.Column('total_budget', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('campaigns', sa.Column('target_audience', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'target_audience')
    op.drop_column('campaigns', 'total_budget')
    op.drop_column('campaigns', 'end_date')
    op.drop_column('campaigns', 'start_date')
    op.drop_column('campaigns', 'objective')
    op.drop_index(op.f('ix_ad_metrics_daily_external_campaign_id'), table_name='ad_metrics_daily')
    op.drop_column('ad_metrics_daily', 'external_campaign_id')
    op.drop_column('ad_metrics_daily', 'segment_data')
    op.drop_column('ad_metrics_daily', 'actions_data')
    op.drop_column('ad_metrics_daily', 'cpm')
    op.drop_column('ad_metrics_daily', 'cpc')
    op.drop_column('ad_metrics_daily', 'ctr')
    op.drop_column('ad_metrics_daily', 'frequency')
    op.drop_column('ad_metrics_daily', 'reach')
    op.drop_index(op.f('ix_meta_ad_breakdowns_breakdown_date'), table_name='meta_ad_breakdowns')
    op.drop_table('meta_ad_breakdowns')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_ga4_traffic_traffic_date'), table_name='ga4_traffic')
    op.drop_table('ga4_traffic')
    op.drop_index(op.f('ix_ga4_item_interactions_item_id'), table_name='ga4_item_interactions')
    op.drop_index(op.f('ix_ga4_item_interactions_interaction_date'), table_name='ga4_item_interactions')
    op.drop_table('ga4_item_interactions')
    op.drop_index(op.f('ix_customers_external_customer_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
